"""auto-votes

Revision ID: 72b067d937d5
Revises: 5542785c995e
Create Date: 2022-02-10 12:16:23.700073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72b067d937d5'
down_revision = '5542785c995e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('name', sa.String(), nullable=False))
    op.add_column('posts', sa.Column('company', sa.String(), nullable=False))
    op.add_column('posts', sa.Column('email', sa.String(), nullable=True))
    op.add_column('posts', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_column('posts', 'title')
    op.drop_column('posts', 'content')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('posts', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('posts', 'created_at')
    op.drop_column('posts', 'email')
    op.drop_column('posts', 'company')
    op.drop_column('posts', 'name')
    # ### end Alembic commands ###
