"""auto-votes

Revision ID: 79579aa9c55c
Revises: f9cb4111e521
Create Date: 2022-02-10 17:34:02.762759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79579aa9c55c'
down_revision = 'f9cb4111e521'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('votes',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'post_id')
    )
    op.add_column('posts', sa.Column('name', sa.String(), nullable=False))
    op.add_column('posts', sa.Column('company', sa.String(), nullable=False))
    op.add_column('posts', sa.Column('email', sa.String(), nullable=True))
    op.drop_column('posts', 'title')
    op.drop_column('posts', 'content')
    op.drop_column('posts', 'published')
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
    op.add_column('posts', sa.Column('published', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.add_column('posts', sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('posts', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('posts', 'email')
    op.drop_column('posts', 'company')
    op.drop_column('posts', 'name')
    op.drop_table('votes')
    # ### end Alembic commands ###
